### PR TITLE
Initial documentation with github pages hosting

### PR DESCRIPTION
**Pull request by nickkprice**
You can see my fork's working pages at at https://nickkprice.github.io/scresonators-docs/
In order to get this working for main, repo owner needs to:
- Merge this pull request
- Navigate to repo settings
- Select pages
image
- Select source branch of main
- Select /docs folder
image

After a few minutes the github page should be up and running. You can also change the URL to something more concise.

### CODE REVIEW

**Comment by scottito** [comment]
@crmcrae @nmaterise this is from a while ago but we should merge this to set up the page as documentation for [scresonators](https://github.com/Boulder-Cryogenic-Quantum-Testbed/scresonators)

**Comment by nmaterise** [comment]
I don't have write-access to this repository. @crmcrae, if you can add me to the list of write-access users for this repository, I can review this and future pull requests. Thanks.

**Comment by crmcrae** [comment]
Okay I gave you "maintain" status - let me know if that works.

**Comment by nmaterise** [comment]
I don’t think that worked. I can’t see the reviewers button.

**Comment by crmcrae** [comment]
Okay you’re now an admin. If that doesn’t work let me know and we can look
together.

**Review by nmaterise — APPROVED** [review]

**Pull request merged**
